### ISSUE TITLE
[bug] Error: failed to get cargo metadata

### ISSUE THREAD

**Issue by thednp** [AR10Dev/tauri-solid-ts-tailwind-vite#104]
### Describe the bug

Hi!

Getting this strange error:
```
Error: failed to get cargo metadata: No such file or directory (os error 2)
```

I'm running an ---AUR container inside VanillaOS, NodeJS 20.x, pnpm latest.

### Steps to Reproduce the Bug or Issue

Once pnpm dev, this pops up.

### Expected behavior

No go..

### Platform and versions

[✘] Environment
    - OS: Arch Linux 20230709.0.163418 X64
    ✘ webkit2gtk-4.0: not installed
      Visit https://tauri.app/v1/guides/getting-started/prerequisites to learn more about tauri prerequisites
    ✔ rsvg2: 2.56.2
    ✘ rustc: not installed!
      Maybe you don't have rust installed! Visit https://rustup.rs/
    ✘ Cargo: not installed!
      Maybe you don't have rust installed! Visit https://rustup.rs/
    ⚠ rustup: not installed!
      If you have rust installed some other way, we recommend uninstalling it
      then use rustup instead. Visit https://rustup.rs/
    ⚠ Rust toolchain: couldn't be detected!
      Maybe you don't have rustup installed? if so, Visit https://rustup.rs/
    - node: 20.10.0
    - pnpm: 9.1.4
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 1.6.2 (no lockfile)
    - tauri-build [RUST]: no manifest (no lockfile)
    - wry [RUST]: no manifest (no lockfile)
    - tao [RUST]: no manifest (no lockfile)
    - @tauri-apps/api [NPM]: 1.5.6
    - @tauri-apps/cli [NPM]: 1.5.14

[-] App
    - build-type: bundle
    - CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
    - distDir: Injected by vite-plugin-tauri
    - devPath: Injected by vite-plugin-tauri
    - framework: SolidJS
    - bundler: Vite

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by AR10Dev** [comment]
Hi, the error message indicates that Cargo, the Rust package manager, can't be found and that Rust might not be installed. Also, all the requirements for Tauri aren't installed, so please make sure you've followed this [guide](https://tauri.app/v1/guides/getting-started/prerequisites/).
