### ISSUE TITLE
[bug] Nothing happens on the rust side as you run the npm run dev command.

### ISSUE THREAD

**Issue by maxjnq** [AR10Dev/tauri-solid-ts-tailwind-vite#95]
### Describe the bug

I simply git clone the repo, runs npm install, npm run dev, the vite dev server starts all good but that's it. No dependencies are installed from Tauri whatsover.

### Steps to Reproduce the Bug or Issue

1. clone repo
2. npm install
3. npm run dev

### Expected behavior

I am expecting something to happen on the Tauri side.

### Platform and versions

both commands ran in my app folder output

maxjnq@Maximes-MacBook-Pro tauri-test % cargo tauri info
error: no such command: `tauri`

maxjnq@Maximes-MacBook-Pro tauri-test % npm run tauri info
npm ERR! Missing script: "tauri"

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by maxjnq** [comment]
After adding tauri: "tauri" in my scripts I get that.

```
maxjnq@Maximes-MacBook-Pro src-tauri % npm run tauri info

> tauri-solid-tailwind-ts-vite-template@1.0.0 tauri
> tauri info

WARNING: Only one package manager should be used, but found npm and pnpm.
         Please remove unused package manager lock files, will use npm for now!

[✔] Environment
    - OS: Mac OS 14.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.77.1 (7cf61ebde 2024-03-27)
    ✔ cargo: 1.77.1 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 21.6.2
    - pnpm: 8.15.5
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 1.6.0
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.0
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.11

[-] App
    - build-type: bundle
    - CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
    - distDir: Injected by vite-plugin-tauri
    - devPath: Injected by vite-plugin-tauri
    - framework: SolidJS
    - bundler: Vite
```

**Comment by AR10Dev** [comment]
To run the Tauri side, use the command `npm run dev:tauri`. 
`npm run dev` is only used for starting the Vite dev server on the frontend side.
